default:
    just --list

build:
    podman build -t spark-base -f base.dockerfile
    podman build -t spark-master -f master.dockerfile
    podman build -t spark-worker -f worker.dockerfile

master:
    podman rm -f spark-master || true
    podman run -d --name spark-master --hostname spark-master --network data-platform -p 8080:8080 -p 7077:7077 spark-master
    podman logs -f spark-master

worker:
    podman rm -f spark-worker || true
    podman run -d --name spark-worker --hostname spark-worker --network data-platform -p 8081:8081 spark-worker
    podman logs -f spark-worker
