version: '3.4'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: my-access-key
      MINIO_SECRET_KEY: my-secret-key
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  minio-init:
    build:
      context: .
      dockerfile: minio-init.dockerfile
    depends_on:
      - minio
    environment:
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: my-access-key
      MINIO_SECRET_KEY: my-secret-key
    
networks:
  default:
    name: data-platform
