version: '3.4'

services:
  datalake-ingest:
    build:
      context: .
      dockerfile: dockerfile
    container_name: datalake-ingest
    ports:
      - "8000:8000"
    environment:
      MINIO_HOST: minio
      MINIO_ACCESS_KEY: my-access-key
      MINIO_SECRET_KEY: my-secret-key

networks:
  default:
    name: data-platform
