default:
    just --list

install:
    poetry install

dev:
    poetry run fastapi dev main.py

up:
    podman compose up -d

down:
    podman compose down -d

push:
    curl \
    --request POST \
    --url http://localhost:8000/event \
    --header 'Content-Type: application/json' \
    --data '{"metadata": {"name": "foobar", "version":"1.0.0", "timestamp":"asdf"}, "payload": {"foo":"bar"}}'
